name: Create changeset for updating linting configs

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create changeset
        run: |
          FILE_PATH=".changeset/lint-config-deps.md"
          echo "---" > $FILE_PATH
          echo '"@4mbl/lint": minor' >> $FILE_PATH
          echo "---" >> $FILE_PATH
          echo "" >> $FILE_PATH
          echo "Upgrade config dependencies" >> $FILE_PATH

          git switch -c create-config-deps-changeset
          git add $FILE_PATH
          git commit -m "chore: create changeset for config deps"
          git push origin HEAD
          gh pr create --title "chore: create changeset for config deps" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
